### ISSUE TITLE
Installation of GGTOOLS

### ISSUE THREAD

**Issue by JoshRasta** [lcx366/GGTOOLS#1]
I couldn't install ggtools on python 3.8.0 because cartopy have not .whl file for this version. Please, give some suggestions. Thank you very much.

**Comment by lcx366** [comment]
The test and installation environment of GGTOOLS is py37. Maybe it would be better for you to switch to py37. Alternatively, it is also possible to suggest Cartopy to upgrade to py38.

**Comment by xiaojingdounaodan** [comment]
你好，
**我用命令pip install ggtools时**
提示ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-twpv1we6\pySphericalPolygon\setup.py", line 6, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 1138: illegal multibyte sequence
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-twpv1we6\pySphericalPolygon\
python版本：3.7.3。
**安装源文件**
提示：Processing dependencies for ggtools==1.1.3
error: numpy 1.16.5 is installed but numpy>=1.17.4 is required by {'pyshtools'}
而我numpy版本是1.17.4，请问如何解决呢？谢谢！
另外，pyshtools已经安装。Requirement already satisfied: pytz>=2011k in h:\anaconda3\envs\python35\lib\site-packages (from pandas>=0.24->xarray->pyshtools) (2019.1)

**Comment by lcx366** [comment]
I have mentioned the 'gbk' error to the developers of pySphericalPolygon a few weeks ago, but they are currently on Christmas, so there is no reply yet. For the solution of this problem, please refer to https://github.com/omrivolk/pySphericalPolygon/issues/3. For the second question, just upgrade numpy with conda or pip.

**Comment by xiaojingdounaodan** [comment]
> I have mentioned the 'gbk' error to the developers of pySphericalPolygon a few weeks ago, but they are currently on Christmas, so there is no reply yet. For the solution of this problem, please refer to [omrivolk/pySphericalPolygon#3](https://github.com/omrivolk/pySphericalPolygon/issues/3). For the second question, just upgrade numpy with conda or pip.

I have tried the method you gave, but the problem still exist by using the two installation method . My numpy version is 1.18.0。I am confused.

**Comment by lcx366** [comment]
By replacing the pySphericalPolygon package with the newly developed **sphericalpolygon** package, the installation issue with GGTOOLS has been fixed. Try reinstalling ggtools or upgrading to the latest version.
